### ISSUE TITLE
feat: add helpers buttons for execution

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#366]
We should add buttons to do execution when a proposal get quorum and we are over the min voting period, the button would look like this:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/16245250/210283432-8d8d4d28-6fa0-463a-a552-3a0885aaa010.png">

**Comment by Sekhmet** [comment]
If we want to make those button functional there are few issues with making it possible:
- Finalize proposal: there is no event broadcast when proposal is finalized so we don't know if this button should be active or not, otherwise broadcasting transaction is simple.

Receive proposal/execute transactions: those two operate on proposalIndex which isn't mapped to proposalId on starknet (it's just incremental ID of received proposals on ETH). Because of this problem it seems impossible to check if transaction was received or executed (using `getProposalState`) or to actually execute transactions (proposalIndex is needed there).

With those limitations we could:
- have all buttons active at the same, user needs to pick the one that makes sense with state of the proposal on the blockchain.
- when executing transactions we would prompt user to provide proposalIndex.

To solve those we would most likely need to make adjustments to the contracts itself.

**Comment by bonustrack** [comment]
@Sekhmet Thanks, we can have all buttons active to start and we will adapt the contracts for next deployments to get the state stored and proposal index accessible from the contract or event. 

@pscott @Orland0x 
- Can we add an event when a proposal is finalized? We need this to be able to show the state of the proposal on the UI. See related issue: https://github.com/snapshot-labs/sx-core/issues/391
- In L1, can we store the current or next proposal index to do the actions "receive proposal" and "execute transactions"? Related issue: https://github.com/snapshot-labs/sx-core/issues/392

**Comment by Sekhmet** [comment]
@bonustrack 

For finalize call we need Starknet account as it's Starknet transaction. Do we want to make it go through mana as well (mana will need to be adjusted to support that then)?

**Comment by bonustrack** [comment]
@Sekhmet We should not use Mana for `finalize_proposal`, there will be few actions like changing quorum or strategies that will require someone authority and we don't have support for signed message for these in the space contract, even if `finalize_proposal` don't need specific permission it's better to keep same flow. Later we may create some kind of keeper to run such functions

**Comment by Orland0x** [comment]
> @Sekhmet We should not use Mana for `finalize_proposal`, there will be few actions like changing quorum or strategies that will require someone authority and we don't have support for signed message for these in the space contract, even if `finalize_proposal` don't need specific permission it's better to keep same flow to not complicate things. Later we may create some kind of keeper to run such functions

id make a distinction between proposal actions like `finalize_proposal` and space controller actions like changing quorum. Unless we do actually plan to ship the keeper bot with the first release I think it will be bad ux to not support `finalize_proposal` with mana. will confuse/annoy a lot of people

**Comment by bonustrack** [comment]
Ok maybe you right, it might be confusing UX wise to login with SN account to finalize a proposal. Can do a simple endpoint in Mana for it without permission, similar than what we have for Fossil actions

**Comment by Sekhmet** [comment]
Thanks guys, updated the PR to implement finalize proposal via Mana: https://github.com/snapshot-labs/sx-ui/pull/373

**Comment by Sekhmet** [comment]
Will close this issue in this PR: https://github.com/snapshot-labs/sx-ui/pull/457.

Starknet doesn't have executed state, so it wasn't possible to implement fully, but given it's unknown when it's going to updated I won't be keeping this issue open longer.
