### ISSUE TITLE
style: space menu should be hidden on proposal and editor pages

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#492]
We shouldn't see the space menu on proposal and editor pages
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/16245250/223934340-15354216-ff2c-4f72-80c4-3eef91a1c7c9.png">

**Comment by j0hnfl0w** [comment]
So if we hide menu on proposal page we need somehow to return to space page
![image](https://user-images.githubusercontent.com/97898172/225908290-85255b3b-a887-4947-9425-18d4ef40e7eb.png)
Just like we can return from editor with btn
![image](https://user-images.githubusercontent.com/97898172/225908481-8469b841-bbda-46c5-a1c6-ee5119464401.png)

**Comment by j0hnfl0w** [comment]
@bonustrack ping

**Comment by Sekhmet** [comment]
@j0hnfl0w it was like this before, this menu being visible is regression from your PR I believe that refactored how routes are  defined, you can check how it looked like before it.

**Comment by Sekhmet** [comment]
I tested latest #508 and found following issues:

Extra bar shows up on explore page:
![image](https://user-images.githubusercontent.com/1968722/232809884-d967722e-6876-488f-baa4-ff26d9b62e6b.png)

Search proposals shows up on proposal page (actually same as master, because I used the same if check as we had for sidebar).
![image](https://user-images.githubusercontent.com/1968722/232810558-19b93d1c-3b83-4cbf-9a96-c49a68562fb7.png)

This tends to have something broken all the time, what do you think of making it a separate PR? It will be easier to review and test if it it's not part of 20 file PR already.
