### ISSUE TITLE
SX-UI: show logged user voting power with Snapshot

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#855]
1. Voting power for voter is calculated by `getVotingPower` method under `network.actions.getVotingPower`: https://github.com/snapshot-labs/sx-ui/blob/5ef9908d881f6917843cfc3ed23b7116e8480b39/src/networks/types.ts#L76-L84
2. Each network type uses different getVotingPower implementation (`starknet`/`evm`/`offchain`).
3. `offchain` network (so one for Snapshot.org) has it defined there (currently it does nothing): https://github.com/snapshot-labs/sx-ui/blob/e8ff1653d4ac152fd1269679fead6d9bfc4f45a7/src/networks/offchain/index.ts#L51-L53
4. The UI displays total voting power (sum of all voting powers for each voting strategy) and per-strategy voting power, so we need to fetch list of strategies (or any extra data you might need to actually calculate voting power (strategy params etc.).
5. You can fetch that data in API for `offchain` network: This data can be then filled in here: https://github.com/snapshot-labs/sx-ui/blob/9ba7992477873cdc42374a844757cfee1130dc1b/src/networks/offchain/api/index.ts#L124-L126
6. It's likely that the shape we have currently for Proposals/Spaces won't really work for Snapshot.org strategies - we can make adjustments to our shape as needed - but I think ideally we would have a integration without much refactoring initially and once we understand all the differences we can come back to it and refactor it to make it seamless.

**Comment by wa0x6e** [comment]
```
getVotingPower( 
     strategiesAddresses: string[], 
     strategiesParams: any[], 
     strategiesMetadata: StrategyParsedMetadata[], 
     voterAddress: string, 
     current: number | null 
   ): Promise<VotingPower[]>; 
```

This function does not conform to the current voting power query on snapshot hub, which only accepts `voter`, `space` and `proposal` as params.

The api instance is connecting to snapshot hub with

https://github.com/snapshot-labs/sx-ui/blob/5344667bcffb88c73f7c6a0260425283c7537e2c/src/networks/offchain/index.ts#L18

and seems that the Network object is made to connect to a single api.

https://github.com/snapshot-labs/sx-ui/blob/5344667bcffb88c73f7c6a0260425283c7537e2c/src/networks/types.ts#L216-L230

I am not familiar with the whole code yet, but seems opinionated toward a single source of truth (api), using graphql, but the voting power on snapshot v1 is fetched directly from score-api

Should we refactor the hub to support queries and api from snapshot v2 ? Seems easier than the other way, adding more specialized code in snapshot v2 to support the hub, which will be deprecated in the long term.

**Comment by wa0x6e** [comment]
We could add a new `/v2/graphlq` on snapshot hub, which will serve only requests from snapshot v2, and return results already formatted 

This will remove all the `formatSpace`, `formatVote` and `formatProposal` functions, and sx-ui will not have to deal with legacy code from snapshot v1.

It will act as a kind of adapter on top of the hub, translating response from snapshot v1 to snapshot v2, instead of having this translation in sx-ui codebase.

**Comment by Sekhmet** [comment]
> This function does not conform to the current voting power query on snapshot hub, which only accepts voter, space and proposal as params.

We don't need to worry about it having too many arguments (we can just ignore those), for those that are missing we can add them. However as you mention it requires proposal as param, it might conflict with what we are doing on SX where it's possible see voting power at specific timestamp, not necessarily specific proposal (this way we can display current voting power on proposals list which isn't tied to current proposal). Is there functionality that would allow it?

Also on SX-UI we display voting power separately for each voting strategy (and sum it up), is it possible to achieve the same with existing hub/score-api?

> I am not familiar with the whole code yet, but seems opinionated toward a single source of truth (api), using graphql, but the voting power on snapshot v1 is fetched directly from score-api

You can make network use as many APIs as you want, it just uses single one now because it was all we needed, but if you need to access score-api there shouldn't be anything preventing you from making calls to that second API (or third, fourth etc.). Network should provide consistent API to the outside (so we can have different types of networks using the same UI), but what's inside can be as specific to the network itself as it needs, using different APIs, more APIs etc.
